export const carsCollections = [{
    brand: "Maruti Suzuki",
    model: "Ertiga VXI",
    year: "2014",
    price: "6.53",
    image: "https://d308ljkq6e62o1.cloudfront.net/img/lPxXIZZ7SpG4kwG3EenkIQ/mobile/file.JPG?w=300&dpr=1.0",
    description: "3 shortlisted this car",
    fuel: "Petrol",
    kmDriven: "20,000 km",
    owners: "1st Owner",
    transmission: "Manual",
    location: "Delhi",
    name: "Rahul",
    contactNumber: "9876543210",
    email: "test@gmail.com",
    actualPrice: "₹ 6,53,000",
},
{
    brand: "Maruti Suzuki",
    model: "Swift",
    year: "2018",
    price: "5.50",
    image: "https://d308ljkq6e62o1.cloudfront.net/img/lPxXIZZ7SpG4kwG3EenkIQ/mobile/file.JPG?w=300&dpr=1.0",
    description: "This is a Maruti Suzuki Swift 2018 model. It is in good condition.",
    fuel: "Petrol",
    kmDriven: "20,000 km",
    owners: "1st Owner",
    transmission: "Manual",
    location: "Delhi",
    name: "Rahul",
    contactNumber: "9876543210",
    email: "test@gmail.com",
    actualPrice: "₹ 6,53,000",
},
{
    brand: "Maruti Suzuki",
    model: "Swift",
    year: "2018",
    price: "5.50",
    image: "https://d308ljkq6e62o1.cloudfront.net/img/lPxXIZZ7SpG4kwG3EenkIQ/mobile/file.JPG?w=300&dpr=1.0",
    description: "This is a Maruti Suzuki Swift 2018 model. It is in good condition.",
    fuel: "Petrol",
    kmDriven: "20,000 km",
    owners: "1st Owner",
    transmission: "Manual",
    location: "Delhi",
    name: "Rahul",
    contactNumber: "9876543210",
    email: "test@gmail.com",
    actualPrice: "₹ 6,53,000",
},
{
    brand: "Maruti Suzuki",
    model: "Swift",
    year: "2018",
    price: "5.50",
    image: "https://d308ljkq6e62o1.cloudfront.net/img/lPxXIZZ7SpG4kwG3EenkIQ/mobile/file.JPG?w=300&dpr=1.0",
    description: "This is a Maruti Suzuki Swift 2018 model. It is in good condition.",
    fuel: "Petrol",
    kmDriven: "20,000 km",
    owners: "1st Owner",
    transmission: "Manual",
    location: "Delhi",
    name: "Rahul",
    contactNumber: "9876543210",
    email: "test@gmail.com",
    actualPrice: "₹ 6,53,000",
},
{
    brand: "Maruti Suzuki",
    model: "Swift",
    year: "2018",
    price: "5.50",
    image: "https://d308ljkq6e62o1.cloudfront.net/img/lPxXIZZ7SpG4kwG3EenkIQ/mobile/file.JPG?w=300&dpr=1.0",
    description: "This is a Maruti Suzuki Swift 2018 model. It is in good condition.",
    fuel: "Petrol",
    kmDriven: "20,000 km",
    owners: "1st Owner",
    transmission: "Manual",
    location: "Delhi",
    name: "Rahul",
    contactNumber: "9876543210",
    email: "test@gmail.com",
    actualPrice: "₹ 6,53,000",
},
{
    brand: "Maruti Suzuki",
    model: "Swift",
    year: "2018",
    price: "5.50",
    image: "https://d308ljkq6e62o1.cloudfront.net/img/lPxXIZZ7SpG4kwG3EenkIQ/mobile/file.JPG?w=300&dpr=1.0",
    description: "This is a Maruti Suzuki Swift 2018 model. It is in good condition.",
    fuel: "Petrol",
    kmDriven: "20,000 km",
    owners: "1st Owner",
    transmission: "Manual",
    location: "Delhi",
    name: "Rahul",
    contactNumber: "9876543210",
    email: "test@gmail.com",
    actualPrice: "₹ 6,53,000",
},
]